"""Apply indexes

Revision ID: 11aa71d6fea4
Revises: d9051f8e144d
Create Date: 2025-10-22 21:48:02.601602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11aa71d6fea4"
down_revision: Union[str, Sequence[str], None] = "d9051f8e144d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Install pg_trgm extension
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_directors_name_trgm",
        "directors",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_genres_name_trgm",
        "genres",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_movie_directors_director_id",
        "movie_directors",
        ["director_id"],
        unique=False,
    )
    op.create_index(
        "idx_movie_directors_movie_id", "movie_directors", ["movie_id"], unique=False
    )
    op.create_index(
        "idx_movie_genres_genre_id", "movie_genres", ["genre_id"], unique=False
    )
    op.create_index(
        "idx_movie_genres_movie_id", "movie_genres", ["movie_id"], unique=False
    )
    op.create_index(
        "idx_movie_stars_movie_id", "movie_stars", ["movie_id"], unique=False
    )
    op.create_index("idx_movie_stars_star_id", "movie_stars", ["star_id"], unique=False)
    op.create_index(
        "idx_movies_description_trgm",
        "movies",
        [sa.literal_column("lower(description)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(description)": "gin_trgm_ops"},
    )
    op.create_index("idx_movies_imdb", "movies", ["imdb"], unique=False)
    op.create_index(
        "idx_movies_name_trgm",
        "movies",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.create_index("idx_movies_price", "movies", ["price"], unique=False)
    op.create_index("idx_movies_votes", "movies", ["votes"], unique=False)
    op.create_index("idx_movies_year", "movies", ["year"], unique=False)
    op.create_index(
        "idx_stars_name_trgm",
        "stars",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_stars_name_trgm",
        table_name="stars",
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.drop_index("idx_movies_year", table_name="movies")
    op.drop_index("idx_movies_votes", table_name="movies")
    op.drop_index("idx_movies_price", table_name="movies")
    op.drop_index(
        "idx_movies_name_trgm",
        table_name="movies",
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.drop_index("idx_movies_imdb", table_name="movies")
    op.drop_index(
        "idx_movies_description_trgm",
        table_name="movies",
        postgresql_using="gin",
        postgresql_ops={"lower(description)": "gin_trgm_ops"},
    )
    op.drop_index("idx_movie_stars_star_id", table_name="movie_stars")
    op.drop_index("idx_movie_stars_movie_id", table_name="movie_stars")
    op.drop_index("idx_movie_genres_movie_id", table_name="movie_genres")
    op.drop_index("idx_movie_genres_genre_id", table_name="movie_genres")
    op.drop_index("idx_movie_directors_movie_id", table_name="movie_directors")
    op.drop_index("idx_movie_directors_director_id", table_name="movie_directors")
    op.drop_index(
        "idx_genres_name_trgm",
        table_name="genres",
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_directors_name_trgm",
        table_name="directors",
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###

    # Drop pg_trgm extension (optional, use with caution)
    op.execute("DROP EXTENSION IF EXISTS pg_trgm CASCADE")
