"""Add count rows to movie model

Revision ID: a7dc7adaef97
Revises: 2bd86d0532b0
Create Date: 2025-11-26 19:31:36.558871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7dc7adaef97"
down_revision: Union[str, Sequence[str], None] = "2bd86d0532b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_unique_constraint(None, 'comment_likes', ['user_id', 'comment_id'])
#     op.create_unique_constraint(None, 'movie_likes', ['user_id', 'movie_id'])
#     op.add_column('movies', sa.Column('rating_average', sa.Float(), nullable=False))
#     op.add_column('movies', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
#     op.add_column('movies', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
#     op.add_column('movies', sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False))
#     op.add_column('movies', sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False))
#     op.create_index(op.f('ix_movies_comment_count'), 'movies', ['comment_count'], unique=False)
#     op.create_index(op.f('ix_movies_favorite_count'), 'movies', ['favorite_count'], unique=False)
#     op.create_index(op.f('ix_movies_like_count'), 'movies', ['like_count'], unique=False)
#     op.create_index(op.f('ix_movies_rating_count'), 'movies', ['rating_count'], unique=False)
#     op.create_unique_constraint(None, 'user_favorite_movies', ['user_id', 'movie_id'])
#     # ### end Alembic commands ###


def upgrade() -> None:
    for column, col_type, default in [
        ("rating_average", sa.Float(), 0.0),
        ("rating_count", sa.Integer(), 0),
        ("like_count", sa.Integer(), 0),
        ("favorite_count", sa.Integer(), 0),
        ("comment_count", sa.Integer(), 0),
    ]:
        op.add_column("movies", sa.Column(column, col_type, nullable=True))
        op.execute(f"UPDATE movies SET {column} = {default}")
        op.alter_column(
            "movies",
            column,
            nullable=False,
            server_default=sa.text(
                f"'{default}'" if isinstance(default, float) else str(default)
            ),
        )
        op.create_index(f"ix_movies_{column}", "movies", [column])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_favorite_movies", type_="unique")
    op.drop_index(op.f("ix_movies_rating_count"), table_name="movies")
    op.drop_index(op.f("ix_movies_like_count"), table_name="movies")
    op.drop_index(op.f("ix_movies_favorite_count"), table_name="movies")
    op.drop_index(op.f("ix_movies_comment_count"), table_name="movies")
    op.drop_column("movies", "comment_count")
    op.drop_column("movies", "favorite_count")
    op.drop_column("movies", "like_count")
    op.drop_column("movies", "rating_count")
    op.drop_column("movies", "rating_average")
    op.drop_constraint(None, "movie_likes", type_="unique")
    op.drop_constraint(None, "comment_likes", type_="unique")
    # ### end Alembic commands ###
