"""Apply fixed indexes

Revision ID: a9c94a11d46f
Revises: 11aa71d6fea4
Create Date: 2025-10-22 23:25:52.678498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c94a11d46f'
down_revision: Union[str, Sequence[str], None] = '11aa71d6fea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_directors_name_trgm'), table_name='directors', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_movie_directors_director_id'), table_name='movie_directors')
    op.drop_index(op.f('idx_movie_stars_star_id'), table_name='movie_stars')
    op.drop_index(op.f('idx_movies_description_trgm'), table_name='movies', postgresql_ops={'lower(description)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_movies_votes'), table_name='movies')
    op.drop_index(op.f('idx_stars_name_trgm'), table_name='stars', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
    
    # Warm up cache for tables and indexes
    op.execute("SELECT * FROM movies WHERE id < 0;")  # Warm movies table
    op.execute("SELECT * FROM movie_genres WHERE movie_id < 0;")  # Warm movie_genres table
    op.execute("SELECT * FROM genres WHERE id < 0;")  # Warm genres table
    op.execute("SELECT * FROM movies WHERE name ILIKE '%unlikely_string%';")  # Warm idx_movies_name_trgm
    op.execute("SELECT * FROM movies WHERE year >= 10000 LIMIT 1;")  # Warm idx_movies_year
    op.execute("SELECT * FROM movies WHERE imdb >= 10.0 LIMIT 1;")  # Warm idx_movies_imdb
    op.execute("SELECT * FROM movies WHERE price <= 0 LIMIT 1;")  # Warm idx_movies_price
    op.execute("SELECT * FROM movie_genres WHERE movie_id < 0;")  # Warm idx_movie_genres_movie_id
    op.execute("SELECT * FROM movie_genres WHERE genre_id < 0;")  # Warm idx_movie_genres_genre_id
    op.execute("SELECT * FROM movie_stars WHERE movie_id < 0;")  # Warm idx_movie_stars_movie_id
    op.execute("SELECT * FROM movie_directors WHERE movie_id < 0;")  # Warm idx_movie_directors_movie_id

    # Run ANALYZE to update statistics
    op.execute("ANALYZE movies;")
    op.execute("ANALYZE movie_genres;")
    op.execute("ANALYZE genres;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_stars_name_trgm'), 'stars', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_movies_votes'), 'movies', ['votes'], unique=False)
    op.create_index(op.f('idx_movies_description_trgm'), 'movies', [sa.literal_column('lower(description)')], unique=False, postgresql_ops={'lower(description)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_movie_stars_star_id'), 'movie_stars', ['star_id'], unique=False)
    op.create_index(op.f('idx_movie_directors_director_id'), 'movie_directors', ['director_id'], unique=False)
    op.create_index(op.f('idx_directors_name_trgm'), 'directors', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
