"""Add cart

Revision ID: ca24729742ad
Revises: a7dc7adaef97
Create Date: 2025-12-12 19:27:48.214187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca24729742ad"
down_revision: Union[str, Sequence[str], None] = "a7dc7adaef97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_carts_id"), "carts", ["id"], unique=False)
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "movie_id", name="uq_cart_movie"),
    )
    op.create_index(op.f("ix_cart_items_id"), "cart_items", ["id"], unique=False)
    op.create_unique_constraint(None, "comment_likes", ["user_id", "comment_id"])
    op.create_unique_constraint(None, "movie_likes", ["user_id", "movie_id"])
    op.alter_column(
        "movies",
        "rating_average",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_movies_rating_average"), table_name="movies")
    op.create_unique_constraint(None, "user_favorite_movies", ["user_id", "movie_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_favorite_movies", type_="unique")
    op.create_index(
        op.f("ix_movies_rating_average"), "movies", ["rating_average"], unique=False
    )
    op.alter_column(
        "movies",
        "rating_average",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "movie_likes", type_="unique")
    op.drop_constraint(None, "comment_likes", type_="unique")
    op.drop_index(op.f("ix_cart_items_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_carts_id"), table_name="carts")
    op.drop_table("carts")
    # ### end Alembic commands ###
