"""temp_migration

Revision ID: cef697126140
Revises: 902dea40b95d
Create Date: 2025-12-28 22:44:39.970237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cef697126140"
down_revision: Union[str, Sequence[str], None] = "902dea40b95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "comment_likes", ["user_id", "comment_id"])
    op.create_unique_constraint(None, "movie_likes", ["user_id", "movie_id"])
    op.create_unique_constraint(None, "user_favorite_movies", ["user_id", "movie_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_favorite_movies", type_="unique")
    op.drop_constraint(None, "movie_likes", type_="unique")
    op.drop_constraint(None, "comment_likes", type_="unique")
    # ### end Alembic commands ###
